[package]
name = "sdl2-opengl-example"
version = "0.1.0"

[[bin]]
name = "sdl2-opengl-example"
path = "src/main.rs"

[dependencies]
gl = "0.6.0"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["ttf", "image"]

